version: '3.0'

services:
  booksservice: 
    build:
      context: ./books
      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    environment:
      - DB_USER="${DB_USER}"
      - DB_NAME="${DB_NAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - POSTGRES_CONTAINER_ID="${POSTGRES_CONTAINER_ID}"
      - API_KEY="${API_KEY}"
      - ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET}"
      - REFRESH_TOKEN_SECRET="${REFRESH_TOKEN_SECRET}"
    command: go run books/main.go -b 0.0.0.0

  authservice:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:9091"
    environment:
      - DB_USER="${DB_USER}"
      - DB_NAME="${DB_NAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - POSTGRES_CONTAINER_ID="${POSTGRES_CONTAINER_ID}"
      - API_KEY="${API_KEY}"
      - ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET}"
      - REFRESH_TOKEN_SECRET="${REFRESH_TOKEN_SECRET}"
    command: go run auth/main.go -b 0.0.0.0
